apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: TalosConfigTemplate
metadata:
  name: test1-md-0
  namespace: default
spec:
  template:
    spec:
      machineType: "join"
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
    nodepool: nodepool-0
  name: test1-md-0
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: test1
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: test1
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
          kind: TalosConfigTemplate
          name: test1-md-0
          namespace: default
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: GCPMachineTemplate
        name: test1-md-0
        namespace: default
      version: 1.16.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: GCPMachineTemplate
metadata:
  name: test1-md-0
  namespace: default
spec:
  template:
    spec:
      instanceType: n1-standard-2
      zone: us-central1-a
      image: projects/my-gcp-project/global/images/talos-capi-test