apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: TalosConfig
metadata:
  name: test1-controlplane-0
  labels:
    cluster.x-k8s.io/cluster-name: test1
spec:
  machineType: init
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
    cluster.x-k8s.io/control-plane: "true"
  name: test1-controlplane-0
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: TalosConfig
      name: test1-controlplane-0
      namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: GCPMachine
    name: test1-controlplane-0
    namespace: default
  version: 1.16.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: GCPMachine
metadata:
  name: test1-controlplane-0
  namespace: default
spec:
  instanceType: n1-standard-2
  zone: us-central1-a
  image: projects/my-gcp-project/global/images/talos-capi-test
  serviceAccounts: {}
  publicIP: true

---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: TalosConfig
metadata:
  name: test1-controlplane-1
  labels:
    cluster.x-k8s.io/cluster-name: test1
spec:
  machineType: controlplane
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
    cluster.x-k8s.io/control-plane: "true"
  name: test1-controlplane-1
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: TalosConfig
      name: test1-controlplane-1
      namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: GCPMachine
    name: test1-controlplane-1
    namespace: default
  version: 1.16.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: GCPMachine
metadata:
  name: test1-controlplane-1
  namespace: default
spec:
  instanceType: n1-standard-2
  zone: us-central1-a
  image: projects/my-gcp-project/global/images/talos-capi-test
  serviceAccounts: {}
  publicIP: true

---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: TalosConfig
metadata:
  name: test1-controlplane-2
  labels:
    cluster.x-k8s.io/cluster-name: test1
spec:
  machineType: controlplane
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
    cluster.x-k8s.io/control-plane: "true"
  name: test1-controlplane-2
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: TalosConfig
      name: test1-controlplane-2
      namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: GCPMachine
    name: test1-controlplane-2
    namespace: default
  version: 1.16.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: GCPMachine
metadata:
  name: test1-controlplane-2
  namespace: default
spec:
  instanceType: n1-standard-2
  zone: us-central1-a
  image: projects/my-gcp-project/global/images/talos-capi-test
  serviceAccounts: {}
  publicIP: true