apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: test1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    apiServerPort: 443
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: GCPCluster
    name: test1
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: GCPCluster
metadata:
  name: test1
  namespace: default
spec:
  project: my-gcp-project
  region: us-central1
