package v1alpha3

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachineryconversion "k8s.io/apimachinery/pkg/conversion"
	"k8s.io/utils/ptr"
	clusterv1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
	clusterv1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
	utilconversion "sigs.k8s.io/cluster-api/util/conversion"
	"sigs.k8s.io/controller-runtime/pkg/conversion"

	bsv1beta1 "github.com/siderolabs/cluster-api-bootstrap-provider-talos/api/v1beta1"
)

// ConvertTo converts this TalosConfig to the Hub version (v1beta1).
func (src *TalosConfig) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*bsv1beta1.TalosConfig)
	if err := Convert_v1alpha3_TalosConfig_To_v1beta1_TalosConfig(src, dst, nil); err != nil {
		return err
	}

	// Preserve Hub data on down-conversion.
	restored := &bsv1beta1.TalosConfig{}
	ok, err := utilconversion.UnmarshalData(src, restored)
	if err != nil || !ok {
		return err
	}

	// Recover intent for bool values converted to *bool.
	initialization := bsv1beta1.TalosConfigInitializationStatus{}
	restoredBootstrapDataSecretCreated := restored.Status.Initialization.DataSecretCreated
	clusterv1beta2.Convert_bool_To_Pointer_bool(src.Status.Ready, ok, restoredBootstrapDataSecretCreated, &initialization.DataSecretCreated)
	if !reflect.DeepEqual(initialization, bsv1beta1.TalosConfigInitializationStatus{}) {
		dst.Status.Initialization = initialization
	}

	return nil
}

// ConvertFrom converts from the Hub version (v1beta1) to this version (v1alpha3).
func (dst *TalosConfig) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*bsv1beta1.TalosConfig)
	if err := Convert_v1beta1_TalosConfig_To_v1alpha3_TalosConfig(src, dst, nil); err != nil {
		return err
	}

	// Preserve Hub data on down-conversion.
	if err := utilconversion.MarshalData(src, dst); err != nil {
		return err
	}

	return nil
}

func (src *TalosConfigList) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*bsv1beta1.TalosConfigList)
	return Convert_v1alpha3_TalosConfigList_To_v1beta1_TalosConfigList(src, dst, nil)
}

func (dst *TalosConfigList) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*bsv1beta1.TalosConfigList)
	return Convert_v1beta1_TalosConfigList_To_v1alpha3_TalosConfigList(src, dst, nil)
}

func (src *TalosConfigTemplate) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*bsv1beta1.TalosConfigTemplate)
	return Convert_v1alpha3_TalosConfigTemplate_To_v1beta1_TalosConfigTemplate(src, dst, nil)
}

func (dst *TalosConfigTemplate) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*bsv1beta1.TalosConfigTemplate)
	return Convert_v1beta1_TalosConfigTemplate_To_v1alpha3_TalosConfigTemplate(src, dst, nil)
}

func (src *TalosConfigTemplateList) ConvertTo(dstRaw conversion.Hub) error {
	dst := dstRaw.(*bsv1beta1.TalosConfigTemplateList)
	return Convert_v1alpha3_TalosConfigTemplateList_To_v1beta1_TalosConfigTemplateList(src, dst, nil)
}

func (dst *TalosConfigTemplateList) ConvertFrom(srcRaw conversion.Hub) error {
	src := srcRaw.(*bsv1beta1.TalosConfigTemplateList)
	return Convert_v1beta1_TalosConfigTemplateList_To_v1alpha3_TalosConfigTemplateList(src, dst, nil)
}

func Convert_v1alpha3_TalosConfigStatus_To_v1beta1_TalosConfigStatus(in *TalosConfigStatus, out *bsv1beta1.TalosConfigStatus, s apimachineryconversion.Scope) error {
	if err := autoConvert_v1alpha3_TalosConfigStatus_To_v1beta1_TalosConfigStatus(in, out, s); err != nil {
		return err
	}

	// Reset conditions from autogenerated conversions
	// NOTE: v1beta1 contract conditions should not be automatically be converted into v1beta2 contract conditions.
	out.Conditions = nil

	// Retrieve new conditions (v1beta2) from the v1beta2 field.
	if in.V1Beta2 != nil {
		out.Conditions = in.V1Beta2.Conditions
	}

	// Move legacy conditions (v1beta1), failureReason and failureMessage to the deprecated field.
	if out.Deprecated == nil {
		out.Deprecated = &bsv1beta1.TalosConfigDeprecatedStatus{}
	}
	if out.Deprecated.V1Beta1 == nil {
		out.Deprecated.V1Beta1 = &bsv1beta1.TalosConfigV1Beta1DeprecatedStatus{}
	}
	if in.Conditions != nil {
		clusterv1beta1.Convert_v1beta1_Conditions_To_v1beta2_Deprecated_V1Beta1_Conditions(&in.Conditions, &out.Deprecated.V1Beta1.Conditions)
	}
	out.Deprecated.V1Beta1.FailureReason = in.FailureReason
	out.Deprecated.V1Beta1.FailureMessage = in.FailureMessage

	return nil
}

func Convert_v1beta1_TalosConfigStatus_To_v1alpha3_TalosConfigStatus(in *bsv1beta1.TalosConfigStatus, out *TalosConfigStatus, s apimachineryconversion.Scope) error {
	if err := autoConvert_v1beta1_TalosConfigStatus_To_v1alpha3_TalosConfigStatus(in, out, s); err != nil {
		return err
	}

	// Reset conditions from autogenerated conversions
	// NOTE: v1beta2 contract conditions should not be automatically be converted into legacy conditions (v1beta1 contract).
	out.Conditions = nil

	// Retrieve legacy conditions (v1beta1), failureReason and failureMessage from the deprecated field.
	if in.Deprecated != nil && in.Deprecated.V1Beta1 != nil {
		if in.Deprecated.V1Beta1.Conditions != nil {
			clusterv1beta1.Convert_v1beta2_Deprecated_V1Beta1_Conditions_To_v1beta1_Conditions(&in.Deprecated.V1Beta1.Conditions, &out.Conditions)
		}
		out.FailureReason = in.Deprecated.V1Beta1.FailureReason
		out.FailureMessage = in.Deprecated.V1Beta1.FailureMessage
	}

	// Move initialization to old fields
	out.Ready = ptr.Deref(in.Initialization.DataSecretCreated, false)

	// Move new conditions (v1beta2) to the v1beta2 field.
	if in.Conditions == nil {
		return nil
	}
	out.V1Beta2 = &TalosConfigV1Beta2Status{}
	out.V1Beta2.Conditions = in.Conditions

	return nil
}

func Convert_v1beta1_Condition_To_v1_Condition(in *clusterv1beta1.Condition, out *metav1.Condition, s apimachineryconversion.Scope) error {
	return clusterv1beta1.Convert_v1beta1_Condition_To_v1_Condition(in, out, s)
}

func Convert_v1_Condition_To_v1beta1_Condition(in *metav1.Condition, out *clusterv1beta1.Condition, s apimachineryconversion.Scope) error {
	return clusterv1beta1.Convert_v1_Condition_To_v1beta1_Condition(in, out, s)
}
