//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1beta1 "github.com/siderolabs/cluster-api-bootstrap-provider-talos/api/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ConfigPatches)(nil), (*v1beta1.ConfigPatches)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_ConfigPatches_To_v1beta1_ConfigPatches(a.(*ConfigPatches), b.(*v1beta1.ConfigPatches), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ConfigPatches)(nil), (*ConfigPatches)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ConfigPatches_To_v1alpha3_ConfigPatches(a.(*v1beta1.ConfigPatches), b.(*ConfigPatches), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostnameSpec)(nil), (*v1beta1.HostnameSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_HostnameSpec_To_v1beta1_HostnameSpec(a.(*HostnameSpec), b.(*v1beta1.HostnameSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.HostnameSpec)(nil), (*HostnameSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_HostnameSpec_To_v1alpha3_HostnameSpec(a.(*v1beta1.HostnameSpec), b.(*HostnameSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TalosConfig)(nil), (*v1beta1.TalosConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosConfig_To_v1beta1_TalosConfig(a.(*TalosConfig), b.(*v1beta1.TalosConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TalosConfig)(nil), (*TalosConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosConfig_To_v1alpha3_TalosConfig(a.(*v1beta1.TalosConfig), b.(*TalosConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TalosConfigList)(nil), (*v1beta1.TalosConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosConfigList_To_v1beta1_TalosConfigList(a.(*TalosConfigList), b.(*v1beta1.TalosConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TalosConfigList)(nil), (*TalosConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosConfigList_To_v1alpha3_TalosConfigList(a.(*v1beta1.TalosConfigList), b.(*TalosConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TalosConfigSpec)(nil), (*v1beta1.TalosConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosConfigSpec_To_v1beta1_TalosConfigSpec(a.(*TalosConfigSpec), b.(*v1beta1.TalosConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TalosConfigSpec)(nil), (*TalosConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosConfigSpec_To_v1alpha3_TalosConfigSpec(a.(*v1beta1.TalosConfigSpec), b.(*TalosConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TalosConfigTemplate)(nil), (*v1beta1.TalosConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosConfigTemplate_To_v1beta1_TalosConfigTemplate(a.(*TalosConfigTemplate), b.(*v1beta1.TalosConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TalosConfigTemplate)(nil), (*TalosConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosConfigTemplate_To_v1alpha3_TalosConfigTemplate(a.(*v1beta1.TalosConfigTemplate), b.(*TalosConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TalosConfigTemplateList)(nil), (*v1beta1.TalosConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosConfigTemplateList_To_v1beta1_TalosConfigTemplateList(a.(*TalosConfigTemplateList), b.(*v1beta1.TalosConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TalosConfigTemplateList)(nil), (*TalosConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosConfigTemplateList_To_v1alpha3_TalosConfigTemplateList(a.(*v1beta1.TalosConfigTemplateList), b.(*TalosConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TalosConfigTemplateResource)(nil), (*v1beta1.TalosConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosConfigTemplateResource_To_v1beta1_TalosConfigTemplateResource(a.(*TalosConfigTemplateResource), b.(*v1beta1.TalosConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TalosConfigTemplateResource)(nil), (*TalosConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosConfigTemplateResource_To_v1alpha3_TalosConfigTemplateResource(a.(*v1beta1.TalosConfigTemplateResource), b.(*TalosConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TalosConfigTemplateSpec)(nil), (*v1beta1.TalosConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosConfigTemplateSpec_To_v1beta1_TalosConfigTemplateSpec(a.(*TalosConfigTemplateSpec), b.(*v1beta1.TalosConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TalosConfigTemplateSpec)(nil), (*TalosConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosConfigTemplateSpec_To_v1alpha3_TalosConfigTemplateSpec(a.(*v1beta1.TalosConfigTemplateSpec), b.(*TalosConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Condition)(nil), (*corev1beta1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Condition_To_v1beta1_Condition(a.(*v1.Condition), b.(*corev1beta1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*TalosConfigStatus)(nil), (*v1beta1.TalosConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_TalosConfigStatus_To_v1beta1_TalosConfigStatus(a.(*TalosConfigStatus), b.(*v1beta1.TalosConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*corev1beta1.Condition)(nil), (*v1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Condition_To_v1_Condition(a.(*corev1beta1.Condition), b.(*v1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.TalosConfigStatus)(nil), (*TalosConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TalosConfigStatus_To_v1alpha3_TalosConfigStatus(a.(*v1beta1.TalosConfigStatus), b.(*TalosConfigStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_ConfigPatches_To_v1beta1_ConfigPatches(in *ConfigPatches, out *v1beta1.ConfigPatches, s conversion.Scope) error {
	out.Op = in.Op
	out.Path = in.Path
	out.Value = in.Value
	return nil
}

// Convert_v1alpha3_ConfigPatches_To_v1beta1_ConfigPatches is an autogenerated conversion function.
func Convert_v1alpha3_ConfigPatches_To_v1beta1_ConfigPatches(in *ConfigPatches, out *v1beta1.ConfigPatches, s conversion.Scope) error {
	return autoConvert_v1alpha3_ConfigPatches_To_v1beta1_ConfigPatches(in, out, s)
}

func autoConvert_v1beta1_ConfigPatches_To_v1alpha3_ConfigPatches(in *v1beta1.ConfigPatches, out *ConfigPatches, s conversion.Scope) error {
	out.Op = in.Op
	out.Path = in.Path
	out.Value = in.Value
	return nil
}

// Convert_v1beta1_ConfigPatches_To_v1alpha3_ConfigPatches is an autogenerated conversion function.
func Convert_v1beta1_ConfigPatches_To_v1alpha3_ConfigPatches(in *v1beta1.ConfigPatches, out *ConfigPatches, s conversion.Scope) error {
	return autoConvert_v1beta1_ConfigPatches_To_v1alpha3_ConfigPatches(in, out, s)
}

func autoConvert_v1alpha3_HostnameSpec_To_v1beta1_HostnameSpec(in *HostnameSpec, out *v1beta1.HostnameSpec, s conversion.Scope) error {
	out.Source = v1beta1.HostnameSource(in.Source)
	return nil
}

// Convert_v1alpha3_HostnameSpec_To_v1beta1_HostnameSpec is an autogenerated conversion function.
func Convert_v1alpha3_HostnameSpec_To_v1beta1_HostnameSpec(in *HostnameSpec, out *v1beta1.HostnameSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_HostnameSpec_To_v1beta1_HostnameSpec(in, out, s)
}

func autoConvert_v1beta1_HostnameSpec_To_v1alpha3_HostnameSpec(in *v1beta1.HostnameSpec, out *HostnameSpec, s conversion.Scope) error {
	out.Source = HostnameSource(in.Source)
	return nil
}

// Convert_v1beta1_HostnameSpec_To_v1alpha3_HostnameSpec is an autogenerated conversion function.
func Convert_v1beta1_HostnameSpec_To_v1alpha3_HostnameSpec(in *v1beta1.HostnameSpec, out *HostnameSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_HostnameSpec_To_v1alpha3_HostnameSpec(in, out, s)
}

func autoConvert_v1alpha3_TalosConfig_To_v1beta1_TalosConfig(in *TalosConfig, out *v1beta1.TalosConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_TalosConfigSpec_To_v1beta1_TalosConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_TalosConfigStatus_To_v1beta1_TalosConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_TalosConfig_To_v1beta1_TalosConfig is an autogenerated conversion function.
func Convert_v1alpha3_TalosConfig_To_v1beta1_TalosConfig(in *TalosConfig, out *v1beta1.TalosConfig, s conversion.Scope) error {
	return autoConvert_v1alpha3_TalosConfig_To_v1beta1_TalosConfig(in, out, s)
}

func autoConvert_v1beta1_TalosConfig_To_v1alpha3_TalosConfig(in *v1beta1.TalosConfig, out *TalosConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TalosConfigSpec_To_v1alpha3_TalosConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TalosConfigStatus_To_v1alpha3_TalosConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TalosConfig_To_v1alpha3_TalosConfig is an autogenerated conversion function.
func Convert_v1beta1_TalosConfig_To_v1alpha3_TalosConfig(in *v1beta1.TalosConfig, out *TalosConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_TalosConfig_To_v1alpha3_TalosConfig(in, out, s)
}

func autoConvert_v1alpha3_TalosConfigList_To_v1beta1_TalosConfigList(in *TalosConfigList, out *v1beta1.TalosConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.TalosConfig, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_TalosConfig_To_v1beta1_TalosConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_TalosConfigList_To_v1beta1_TalosConfigList is an autogenerated conversion function.
func Convert_v1alpha3_TalosConfigList_To_v1beta1_TalosConfigList(in *TalosConfigList, out *v1beta1.TalosConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha3_TalosConfigList_To_v1beta1_TalosConfigList(in, out, s)
}

func autoConvert_v1beta1_TalosConfigList_To_v1alpha3_TalosConfigList(in *v1beta1.TalosConfigList, out *TalosConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TalosConfig, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_TalosConfig_To_v1alpha3_TalosConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_TalosConfigList_To_v1alpha3_TalosConfigList is an autogenerated conversion function.
func Convert_v1beta1_TalosConfigList_To_v1alpha3_TalosConfigList(in *v1beta1.TalosConfigList, out *TalosConfigList, s conversion.Scope) error {
	return autoConvert_v1beta1_TalosConfigList_To_v1alpha3_TalosConfigList(in, out, s)
}

func autoConvert_v1alpha3_TalosConfigSpec_To_v1beta1_TalosConfigSpec(in *TalosConfigSpec, out *v1beta1.TalosConfigSpec, s conversion.Scope) error {
	out.TalosVersion = in.TalosVersion
	out.GenerateType = in.GenerateType
	out.Data = in.Data
	out.ConfigPatches = *(*[]v1beta1.ConfigPatches)(unsafe.Pointer(&in.ConfigPatches))
	out.StrategicPatches = *(*[]string)(unsafe.Pointer(&in.StrategicPatches))
	if err := Convert_v1alpha3_HostnameSpec_To_v1beta1_HostnameSpec(&in.Hostname, &out.Hostname, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_TalosConfigSpec_To_v1beta1_TalosConfigSpec is an autogenerated conversion function.
func Convert_v1alpha3_TalosConfigSpec_To_v1beta1_TalosConfigSpec(in *TalosConfigSpec, out *v1beta1.TalosConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_TalosConfigSpec_To_v1beta1_TalosConfigSpec(in, out, s)
}

func autoConvert_v1beta1_TalosConfigSpec_To_v1alpha3_TalosConfigSpec(in *v1beta1.TalosConfigSpec, out *TalosConfigSpec, s conversion.Scope) error {
	out.TalosVersion = in.TalosVersion
	out.GenerateType = in.GenerateType
	out.Data = in.Data
	out.ConfigPatches = *(*[]ConfigPatches)(unsafe.Pointer(&in.ConfigPatches))
	out.StrategicPatches = *(*[]string)(unsafe.Pointer(&in.StrategicPatches))
	if err := Convert_v1beta1_HostnameSpec_To_v1alpha3_HostnameSpec(&in.Hostname, &out.Hostname, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TalosConfigSpec_To_v1alpha3_TalosConfigSpec is an autogenerated conversion function.
func Convert_v1beta1_TalosConfigSpec_To_v1alpha3_TalosConfigSpec(in *v1beta1.TalosConfigSpec, out *TalosConfigSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TalosConfigSpec_To_v1alpha3_TalosConfigSpec(in, out, s)
}

func autoConvert_v1alpha3_TalosConfigStatus_To_v1beta1_TalosConfigStatus(in *TalosConfigStatus, out *v1beta1.TalosConfigStatus, s conversion.Scope) error {
	// WARNING: in.Ready requires manual conversion: does not exist in peer-type
	if err := v1.Convert_Pointer_string_To_string(&in.DataSecretName, &out.DataSecretName, s); err != nil {
		return err
	}
	// WARNING: in.TalosConfig requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureReason requires manual conversion: does not exist in peer-type
	// WARNING: in.FailureMessage requires manual conversion: does not exist in peer-type
	out.ObservedGeneration = in.ObservedGeneration
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	// WARNING: in.V1Beta2 requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_TalosConfigStatus_To_v1alpha3_TalosConfigStatus(in *v1beta1.TalosConfigStatus, out *TalosConfigStatus, s conversion.Scope) error {
	// WARNING: in.Initialization requires manual conversion: does not exist in peer-type
	if err := v1.Convert_string_To_Pointer_string(&in.DataSecretName, &out.DataSecretName, s); err != nil {
		return err
	}
	out.ObservedGeneration = in.ObservedGeneration
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	// WARNING: in.Deprecated requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha3_TalosConfigTemplate_To_v1beta1_TalosConfigTemplate(in *TalosConfigTemplate, out *v1beta1.TalosConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_TalosConfigTemplateSpec_To_v1beta1_TalosConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_TalosConfigTemplate_To_v1beta1_TalosConfigTemplate is an autogenerated conversion function.
func Convert_v1alpha3_TalosConfigTemplate_To_v1beta1_TalosConfigTemplate(in *TalosConfigTemplate, out *v1beta1.TalosConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_TalosConfigTemplate_To_v1beta1_TalosConfigTemplate(in, out, s)
}

func autoConvert_v1beta1_TalosConfigTemplate_To_v1alpha3_TalosConfigTemplate(in *v1beta1.TalosConfigTemplate, out *TalosConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TalosConfigTemplateSpec_To_v1alpha3_TalosConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TalosConfigTemplate_To_v1alpha3_TalosConfigTemplate is an autogenerated conversion function.
func Convert_v1beta1_TalosConfigTemplate_To_v1alpha3_TalosConfigTemplate(in *v1beta1.TalosConfigTemplate, out *TalosConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_TalosConfigTemplate_To_v1alpha3_TalosConfigTemplate(in, out, s)
}

func autoConvert_v1alpha3_TalosConfigTemplateList_To_v1beta1_TalosConfigTemplateList(in *TalosConfigTemplateList, out *v1beta1.TalosConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.TalosConfigTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_TalosConfigTemplateList_To_v1beta1_TalosConfigTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_TalosConfigTemplateList_To_v1beta1_TalosConfigTemplateList(in *TalosConfigTemplateList, out *v1beta1.TalosConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_TalosConfigTemplateList_To_v1beta1_TalosConfigTemplateList(in, out, s)
}

func autoConvert_v1beta1_TalosConfigTemplateList_To_v1alpha3_TalosConfigTemplateList(in *v1beta1.TalosConfigTemplateList, out *TalosConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]TalosConfigTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_TalosConfigTemplateList_To_v1alpha3_TalosConfigTemplateList is an autogenerated conversion function.
func Convert_v1beta1_TalosConfigTemplateList_To_v1alpha3_TalosConfigTemplateList(in *v1beta1.TalosConfigTemplateList, out *TalosConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_TalosConfigTemplateList_To_v1alpha3_TalosConfigTemplateList(in, out, s)
}

func autoConvert_v1alpha3_TalosConfigTemplateResource_To_v1beta1_TalosConfigTemplateResource(in *TalosConfigTemplateResource, out *v1beta1.TalosConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_TalosConfigSpec_To_v1beta1_TalosConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_TalosConfigTemplateResource_To_v1beta1_TalosConfigTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_TalosConfigTemplateResource_To_v1beta1_TalosConfigTemplateResource(in *TalosConfigTemplateResource, out *v1beta1.TalosConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_TalosConfigTemplateResource_To_v1beta1_TalosConfigTemplateResource(in, out, s)
}

func autoConvert_v1beta1_TalosConfigTemplateResource_To_v1alpha3_TalosConfigTemplateResource(in *v1beta1.TalosConfigTemplateResource, out *TalosConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_TalosConfigSpec_To_v1alpha3_TalosConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TalosConfigTemplateResource_To_v1alpha3_TalosConfigTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_TalosConfigTemplateResource_To_v1alpha3_TalosConfigTemplateResource(in *v1beta1.TalosConfigTemplateResource, out *TalosConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_TalosConfigTemplateResource_To_v1alpha3_TalosConfigTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_TalosConfigTemplateSpec_To_v1beta1_TalosConfigTemplateSpec(in *TalosConfigTemplateSpec, out *v1beta1.TalosConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_TalosConfigTemplateResource_To_v1beta1_TalosConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_TalosConfigTemplateSpec_To_v1beta1_TalosConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_TalosConfigTemplateSpec_To_v1beta1_TalosConfigTemplateSpec(in *TalosConfigTemplateSpec, out *v1beta1.TalosConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_TalosConfigTemplateSpec_To_v1beta1_TalosConfigTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_TalosConfigTemplateSpec_To_v1alpha3_TalosConfigTemplateSpec(in *v1beta1.TalosConfigTemplateSpec, out *TalosConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_TalosConfigTemplateResource_To_v1alpha3_TalosConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TalosConfigTemplateSpec_To_v1alpha3_TalosConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_TalosConfigTemplateSpec_To_v1alpha3_TalosConfigTemplateSpec(in *v1beta1.TalosConfigTemplateSpec, out *TalosConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TalosConfigTemplateSpec_To_v1alpha3_TalosConfigTemplateSpec(in, out, s)
}
